// This file is automatically generated by gen_reverb_time.sh script
package reverb_pkg;
localparam NUM = 64;
typedef logic [15:0] reverb_refl_time_t [NUM-1:0];
  localparam reverb_pkg::reverb_refl_time_t DELAYS = '{
   `include "reverb_times_64.vh"
  };
endpackage
